export const sehirler = [
  { value: "Edirne", name: "Edirne" },
  { value: "Ankara", name: "Ankara" },
  { value: "Malatya", name: "Malatya" },
  { value: "", name: "" },
];

export const data = [
  {
    id: 1,
    firma: "Oz Malatya",
    fiyat: 300,
    saat: "21.00",
    nerden: sehirler[0].value,
    nereye: sehirler[2].value,
    tarih: new Date("5-23-2022"),
    koltuklar: [
      { id: 1, satinAlindi: 0 },
      { id: 2, satinAlindi: 0 },
      { id: 3, satinAlindi: 1 },
      { id: 4, satinAlindi: 0 },
      { id: 5, satinAlindi: 0 },
      { id: 6, satinAlindi: 1 },
      { id: 7, satinAlindi: 0 },
      { id: 8, satinAlindi: 1 },
      { id: 9, satinAlindi: 1 },
      { id: 10, satinAlindi: 0 },
      { id: 11, satinAlindi: 0 },
      { id: 12, satinAlindi: 0 },
    ],
  },

  {
    id: 2,
    firma: "Metro",
    fiyat: 350,
    saat: "21.00",
    nerden: sehirler[0].value,
    nereye: sehirler[1].value,
    tarih: new Date("5-23-2022"),
    koltuklar: [
      { id: 1, satinAlindi: 1 },
      { id: 2, satinAlindi: 0 },
      { id: 3, satinAlindi: 0 },
      { id: 4, satinAlindi: 0 },
      { id: 5, satinAlindi: 0 },
      { id: 6, satinAlindi: 0 },
      { id: 7, satinAlindi: 1 },
      { id: 8, satinAlindi: 1 },
      { id: 9, satinAlindi: 0 },
      { id: 10, satinAlindi: 0 },
      { id: 11, satinAlindi: 0 },
      { id: 12, satinAlindi: 0 },
    ],
  },

  {
    id: 3,
    firma: "Zafer",
    saat: "9.00",
    fiyat: 270,
    nerden: sehirler[0].value,
    nereye: sehirler[2].value,
    tarih: new Date("5-23-2022"),
    koltuklar: [
      { id: 1, satinAlindi: 0 },
      { id: 2, satinAlindi: 0 },
      { id: 3, satinAlindi: 0 },
      { id: 4, satinAlindi: 0 },
      { id: 5, satinAlindi: 0 },
      { id: 6, satinAlindi: 1 },
      { id: 7, satinAlindi: 0 },
      { id: 8, satinAlindi: 0 },
      { id: 9, satinAlindi: 1 },
      { id: 10, satinAlindi: 0 },
      { id: 11, satinAlindi: 0 },
      { id: 12, satinAlindi: 0 },
    ],
  },
];
